services:
  postgres:
    image: postgres:17
    container_name: local-postgres
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: conuhacks
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
